# Generated by Django 3.2.25 on 2026-08-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='Main Course', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Restaurant Cover Image', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
